[platformio]
default_envs = m5stack-stamps3

[env:m5stack-stamps3]
platform = espressif32
board = m5stack-stamps3
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
  m5stack/M5DinMeter
  m5stack/M5Unified
  m5stack/M5GFX
  https://github.com/CytronTechnologies/CytronMotorDriver.git
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
